# fly.toml file generated for latitude-embedding-example on 2024-03-25T19:02:06+01:00

app = "latitude-embedding-example"

kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
processes = []

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
